### ISSUE TITLE
Add styling to the search-bar suggestions

### ISSUE THREAD

**Issue by HarshInvader** [IndiaVaccineIN/india-vaccine-frontend#10]
Similar to VaccinateCA for now. Currently the implementation uses the native browser interface for the list of districts

**References**

- https://www.vaccinateca.com

<img width="788" alt="image" src="https://user-images.githubusercontent.com/27439197/117101297-82220f00-ad93-11eb-83a6-77827f3d38c7.png">

- Downshift by Kent C Dotts
    - https://www.downshift-js.com
    - https://github.com/downshift-js/downshift
    - [Codesandbox example](https://codesandbox.io/s/blue-forest-deutw)

**Comment by rahuldkjain** [comment]
@HarshInvader I would love to improve the search dropdown. Please assign it to me.
