### ISSUE TITLE
🐛 Make dropdown filter results as you type

### ISSUE THREAD

**Issue by HarshInvader** [IndiaVaccineIN/india-vaccine-frontend#25]
Currently dropdown shows a fixed list

**Comment by shubh128** [comment]
Hey
I could fix this issue could you assign me this?

**Comment by preetjdp** [comment]
@rahuldkjain Has already taken this up and made a PR 🚀

https://github.com/IndiaVaccineIN/india-vaccine-frontend/pull/27
