### ISSUE TITLE
Feature: Add language support for Marathi (mr-in)

### ISSUE THREAD

**Issue by kshitizshakya** [IndiaVaccineIN/india-vaccine-frontend#29]
Overview:

Currently, the main page of the IndiaVaccine Website is in English & Hindi. We'd like to make the content accessible to more people around the country. In order to do so, we've had translators convert the content into Marathi.

Task Details
We're using . You will need to take the content in Marathi from the document below & update it so that the text appears on the website.

Translation document: https://docs.google.com/spreadsheets/d/1WAnvR9CTLdVDaX5GTLzcNI8mAdeG92JYKT_zoSBcn8Y/edit#gid=1358420706

Task List:

- [ ]  Add Marathi language hyperlink on the main page
- [ ]  Update the overall content with the Marathi translation

**Comment by krishana05** [comment]
I am working on this issue.

**Comment by preetjdp** [comment]
Closing this PR, as it was shipped to the main website

Thanks for working on it @krishana05 

https://www.indiavaccine.in
