### ISSUE TITLE
Feature: Add language support for Telugu(te)

### ISSUE THREAD

**Issue by kshitizshakya** [IndiaVaccineIN/india-vaccine-frontend#30]
Overview:

Currently, the main page of the IndiaVaccine Website is in English & Hindi. We'd like to make the content accessible to more people around the country. In order to do so, we've had translators convert the content into Telugu.

Task Details
We're using . You will need to take the content in Telugu from the document below & update it so that the text appears on the website.

Translation document: https://docs.google.com/spreadsheets/d/1WAnvR9CTLdVDaX5GTLzcNI8mAdeG92JYKT_zoSBcn8Y/edit#gid=1358420706

Task List:

- [ ]  Add Telugu language hyperlink on the main page
- [ ]  Update the overall content with the Telugu translation

**Comment by krishana05** [comment]
I am working on this issue.

**Comment by g-savitha** [comment]
I Would like to work on this issue

**Comment by krishana05** [comment]
I have already made the change and raise the PR for all localisation.

**Comment by g-savitha** [comment]
I didnt see any PR related to that, hence I raised a new one

**Comment by krishana05** [comment]
That's fine. But because all the localisation were similar so thought to raise one PR having all the changes.
The issue were assigned so that we can avoid duplicate effort.

**Comment by preetjdp** [comment]
Closing this PR, as it was shipped to the main website

Thanks for working on it @g-savitha  

https://www.indiavaccine.in
