### ISSUE TITLE
Feature: Add language support for Gujrati(gu-in)

### ISSUE THREAD

**Issue by kshitizshakya** [IndiaVaccineIN/india-vaccine-frontend#32]
Objective:

As a CVC, i should be able to comprehend the content of the website, this can be done supporting vernacular language.

Translation document : https://docs.google.com/spreadsheets/d/1WAnvR9CTLdVDaX5GTLzcNI8mAdeG92JYKT_zoSBcn8Y/edit#gid=1358420706

**Comment by chavda-bhavik** [comment]
I want to work on this issue, can you assign this to me?

**Comment by kshitizshakya** [comment]
@chavda-bhavik  
done.  👍 
Please feel free to assign yourself for any future work.  😃
