### ISSUE TITLE
Feature: Add language support for Gujarati

### ISSUE THREAD

**Issue by Apuroop** [IndiaVaccineIN/india-vaccine-frontend#36]
**Overview:**

Currently, the main page of the IndiaVaccine Website is in English & Hindi. We'd like to make the content accessible to more people around the country. In order to do so, we've had translators convert the content into Gujarati.

**Task Details**
We're using . You will need to take the content in Gujarati from the document below & update it so that the text appears on the website.

**Translation document:** https://docs.google.com/spreadsheets/d/1WAnvR9CTLdVDaX5GTLzcNI8mAdeG92JYKT_zoSBcn8Y/edit#gid=1358420706

**Task List:**
- [ ]  Add Gujarati language hyperlink on the main page
- [ ]  Update the overall content with the Gujarati translation

**Comment by Apuroop** [comment]
@preetjdp You had done some work on this, right?

I think that the initial assessment was that it looked alright. If so, can we update this?

**Comment by preetjdp** [comment]
The Gujarati translation is merged to dev

I think we can close this issue

https://india-vaccine-dev.vercel.app

**Comment by preetjdp** [comment]
Closing this issue, since Gujarati support was brought in
