### ISSUE TITLE
Feature: Add language support for Punjabi

### ISSUE THREAD

**Issue by Apuroop** [IndiaVaccineIN/india-vaccine-frontend#39]
Overview:
Currently, the main page of the IndiaVaccine Website is in English & Hindi. We'd like to make the content accessible to more people around the country. In order to do so, we've had translators convert the content into Punjabi.

Task Details
We're using . You will need to take the content in Punjabi from the document below & update it so that the text appears on the website.

Translation document: https://docs.google.com/spreadsheets/d/1WAnvR9CTLdVDaX5GTLzcNI8mAdeG92JYKT_zoSBcn8Y/edit#gid=1358420706

Task List:

- [x]  Add Punjabi language hyperlink on the main page
- [x]  Update the overall content with the Punjabi translation

**Comment by g-savitha** [comment]
Please assign this to me

**Comment by preetjdp** [comment]
> Please assign this to me

@g-savitha, @SandeepSharma1995 Has already taken this issue up

**Comment by g-savitha** [comment]
Sure
