### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by preetjdp** [IndiaVaccineIN/india-vaccine-frontend#49]
Overview

Add google analytics to the Indian vaccine website, we can also export the [core web vitals](https://web.dev/vitals/) to google analytics

Task List
- [x] Add the GA script to the next JS application
- [x] Add the env for GA_ID
- [ ] Export the core web-vitals [This is optional]

References

- https://stackoverflow.com/questions/60411351/how-to-use-google-analytics-with-next-js-app
- https://nextjs.org/docs/advanced-features/measuring-performance#sending-results-to-analytics

**Comment by rahuldkjain** [comment]
@preetjdp Please assign this issue to me.

**Comment by g-savitha** [comment]
What's the use of adding GA?

**Comment by preetjdp** [comment]
> What's the use of adding GA?

Primarily to get page views data, we don't want to collect any other information right now
